version: '3.9'

services:
  app:
    container_name: rhizome
    build:
      context: .
      target: runtime_stage
      args:
        - NODE_ENV=${NODE_ENV}
        - SERVER_PORT=${SERVER_PORT}
        - DB_MIGRATIONS=${DB_MIGRATIONS}
    volumes:
      - content:/app/content
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy

  database:
    container_name: database
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  cache:
    container_name: cache
    image: redis:7.4.1
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli -a $REDIS_PASSWORD ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
    env_file: .env
    volumes:
      - cache:/data

volumes:
  pgdata:
  content:
  cache:
    driver: local
