version: '3.8'

services:
  app:
    container_name: rhizome
    build:
      context: .
      target: runtime_stage
      args:
        - NODE_ENV=${NODE_ENV}
        - SERVER_PORT=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: always
    env_file: .env
    depends_on:
      cache:
        condition: service_healthy

  cache:
    container_name: redis
    image: redis:7.4.1
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $REDIS_PASSWORD ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
    env_file: .env
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local